// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';
import NavigationDropdownController
  from '../../components/navigation_dropdown_component/navigation_dropdown_controller';
import FlashController
  from '../../components/flash_component/flash_controller';
import NavigationController from './navigation_controller';
import Select2SingleTagController from './select2_single_tag_controller';

application.register('navigation-dropdown', NavigationDropdownController);
application.register('navigation', NavigationController);
application.register('flash', FlashController);
application.register('select2-single-tag', Select2SingleTagController);
