// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';
import NavigationDropdownController
  from '../../components/navigation_dropdown_component/navigation_dropdown_controller';
import ParticipationsTeamController from './participations_team_controller';

application.register('navigation-dropdown', NavigationDropdownController);
application.register('participations-team', ParticipationsTeamController);
