version: "3.7"

x-base: &base
  image: ghcr.io/yannis/kasaharacup
  environment:
    - POSTGRES_HOST=database
    - REDIS_URL=redis://redis:6379
  volumes:
    - $PWD:/app:delegated
    - bundle_cache:/usr/local/bundle:cached
    - node_modules:/app/node_modules:cached
  tty: true
  stdin_open: true

services:
  app:
    <<: *base
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - "80:3000"
    depends_on:
      - database
      - redis
      - js

  js:
    <<: *base
    command: yarn build --watch
    depends_on:
      - css

  css:
    <<: *base
    command: yarn build:css --watch

  database:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data:cached

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data:cached

  sidekiq:
    <<: *base
    command: bundle exec sidekiq -q default -q mailers
    depends_on:
      - database
      - redis

volumes:
  db_data:
  redis_data:
  bundle_cache:
  node_modules:
