version: "3.7"

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
    - .env.override
  environment:
    - POSTGRES_HOST=database
    - SELENIUM_REMOTE_HOST=selenium-chrome
  volumes:
    - $PWD:/app:delegated
    - bundle_cache:/usr/local/bundle:cached
    - node_modules:/app/node_modules:cached
  tty: true
  stdin_open: true

services:
  app:
    <<: *base
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - "80:3000"
    depends_on:
      - database
      - js
      - selenium-chrome

  js:
    <<: *base
    command: yarn build --watch
    depends_on:
      - css

  css:
    <<: *base
    command: yarn build:css --watch

  database:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data:cached
      - db_dump:/app/db_dump:cached

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2G
    logging:
      driver: none
    ports:
      - 5900:5900
    environment:
      - SCREEN_WIDTH=1680
      - SCREEN_HEIGHT=1050
    extra_hosts:
      - "host.docker.internal:host-gateway" # To work on Linux

volumes:
  db_data:
  db_dump:
  bundle_cache:
  node_modules:
