
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kasaharacup_development
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  user: postgres

test:
  <<: *default
  database: kasaharacup_test<%= ENV["TEST_ENV_NUMBER"] %>
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  user: postgres

production:
  <<: *default
  database: kasaharacup_production
  username: kasaharacup
  password: <%= ENV["KASAHARACUP_DATABASE_PASSWORD"] %>
