name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**/main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=test" >> .env.override
          echo "RAILS_ENV=test" >> .env.override
          echo "CI=true" >> .env.override
          echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> .env.override

      - name: Set the right tag/label name in Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/yannis/kasaharacup-app
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push it to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/yannis/kasaharacup-app:buildcache
          cache-to: type=registry,ref=ghcr.io/yannis/kasaharacup-app:buildcache,mode=max

      - name: Modify docker-compose.yml to use the specific Docker image and label
        run: |
          yq 'del(.x-base.build) | .x-base.image = "ghcr.io/yannis/kasaharacup-app:${{ steps.meta.outputs.version }}"' docker-compose.yml -i

      - name: Rubocop
        run: docker-compose run --rm app bundle exec rubocop --parallel -c .rubocop.yml

      - name: Setup database
        run: docker-compose run --rm app bundle exec rake db:drop db:create db:migrate

      - name: Run Rspec
        run: docker-compose run --rm app bundle exec rspec
