name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '**/main'

jobs:
  kasaharacup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: yannis/kasaharacup-app
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=test" >> .env.override
          echo "RAILS_ENV=test" >> .env.override
          echo "CI=true" >> .env.override
          echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> .env.override
      - name: Setup database
        run: docker-compose run --rm app bundle exec rake db:drop db:create db:migrate

      - name: Run Rspec
        run: docker-compose run --rm app bundle exec rspec
